# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1554da95f011445758d0fb310440dd747fe7b609f0c15a2ffeedbedb4451a743d1dca6ac9cd587fec917c22f4f13e469e6818614a4425e60b2696c5bd4a978e2

test:
  secret_key_base: 0b8c63ca72b5a9cce3de42730d3454a37ab97e51fb1ac3f4e0e89e3f8af5dd6dc7458ef2a8b88a41e0cb2c6075434fd130eca624f632b38c62f7ce2e0579361b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
